export const AUTH_USER_LOGIN = 'AUTH/USER_LOGIN';
export const AUTH_SELLER_LOGIN = 'AUTH/SELLER_LOGIN';
export const AUTH_SIGN_UP = 'AUTH/SIGN_UP';
export const AUTH_SET_USER = 'AUTH/SET_USER';
export const AUTH_LOGOUT = 'AUTH/LOGOUT';
export const AUTH_ADMIN_LOGIN = 'AUTH/ADMIN_LOGIN';

export const USER_CART = 'USER/CART_ITEMS';
export const UPDATE_CART_ITEMS = 'UPDATE/CART_ITEMS';
