export enum CART_INC_DEC {
  INCREMENT = 'INCREMENT',
  DECREMENT = 'DECREMENT',
}

export enum INPUT_COMPONENT {
  TEXT = 'TEXT',
  SINGLE_SELECT = 'SINGLE_SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
  DATE_PICKER = 'DATE_PICKER',
}

export enum CRUD {
  CREATE = 'CREATE',
  VIEW = 'VIEW',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
}
